---
application:
  name: "docker-node-hello-world"
  project: "asapasap"
  organization: "QoveryCommunity"
databases:
- type: postgresql
  version: 12
  name: my-postgresql
routers:
- name: "main-docker-node-hello-world"
  routes:
  - application_name: "docker-node-hello-world"
    paths:
    - "/*"
